### PR TITLE
Upgrade to Bootstrap 2

### PR DESCRIPTION
**Pull request by j4mie**
Also reworked the profile list to use Bootstrap thumbnails (with some custom tweaks to remove the border/shadows) so they line up a bit better.

I've moved the Bootstrap CSS into the `media` directory as the Bootstrap docs site no longer seems to encourage hotlinking it. I tried adding the responsive stylesheet, but it screwed things up due to the custom width set on `.container`. Probably not too trick to fix.

### CODE REVIEW

**Comment by almost** [comment]
Thanks Jamie! Upgrading to Bootstrap 2.0 was definitely needed.

A few small problems I'm seeing at the moment:
- Extra space is showing up above the and below the top bar
- Presence indicators are no longer showing over the images
- Divider line is gone between the main contents and the tweets (does this matter? not sure)

Are you planning on coming to the mini-SkiffHack on Friday afternoon? Maybe we can sort out these issues then? 

Thanks again for contributing!

**Comment by j4mie** [comment]
Hmm. What browser? I thought I'd fixed all that stuff..

**Comment by almost** [comment]
Haha, yes, important details :p

It's Chrome on Snow Leopard. If you still can't see it I can send screenshots or show you on my laptop tomorrow at BrightonPy...

**Comment by j4mie** [comment]
I'll have a look when I get a chance!

**Pull request merged**
